version: '3.7'

services:
    server:
        image: php:7.4-apache
        ports:
            - 3000:80
        volumes:
            - "./src:/var/www/html"
    
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            - ./database:/docker-entrypoint-initdb.d

    adminer:
        image: adminer
        ports:
            - 8080:8080